global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['host.docker.internal:9091'] 

    honor_labels: true

    # relabel_configs:
    #   - source_labels: ['__address__']
    #     regex: '(.*):9091'
    #     target_label: 'instance'
    #     replacement: '$1'
    #     action: replace